name: Commit Benachrichtigungen

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Sende Commit-Benachrichtigung an Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            **Repository**: {{ github.repository }}
            **Branch**: {{ github.ref }}
            **Committer**: {{ commit.author.name }}
            **Datum**: {{ commit.timestamp }}
            **Dateien**:
            {% for file in commit.files %}
              - {{ file.filename }}
            {% endfor %}
          embed: false
