name: Pull-Request Benachrichtigungen

on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Sende Pull-Request-Benachrichtigung an Discord
        uses: Ilshidur/action-discord@0.3.2
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          content: |
            **Event**: ${{ github.event_name }}
            **Repository**: ${{ github.repository }}
            **User**: ${{ github.actor }}
            **URL**: ${{ github.event.pull_request.html_url }}
            **Beschreibung**: ${{ github.event.pull_request.body }}
