name: Commit Benachrichtigungen

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Sende Commit-Benachrichtigung an Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: |
            {
              "embed": {
                "title": "{{ commit.title }}",
                "description": "{{ commit.description }}",
                "url": "{{ commit.url }}",
                "author": {
                  "name": "{{ commit.author.name }}",
                  "icon_url": "https://github.com/{{ commit.author.username }}.png"
                },
                "fields": [
                  {
                    "name": "Committer",
                    "value": "{{ commit.author.name }}",
                    "inline": true
                  },
                  {
                    "name": "Datum",
                    "value": "{{ commit.timestamp }}",
                    "inline": true
                  },
                  {
                    "name": "Dateien",
                    "value": "{% for file in commit.files %}- {{ file.filename }}{% endfor %}",
                    "inline": false
                  }
                ]
              }
            }
          include-extras: true
