name: Discord Commits
on:
  push:
    branches:
      - main  # Passen Sie dies an den Namen Ihres Hauptbranches an

jobs:
  discord_notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Sende Nachricht an Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
