name: Discord Notifications

on:
  pull_request:
    types:
      - opened
      - closed
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification to Discord
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{
                "content": "**Event**: '${{ github.event_name }}'\n**Repository**: '${{ github.repository }}'\n**User**: '${{ github.actor }}'\n**URL**: '${{ github.event.pull_request.html_url || github.event.release.html_url || github.event.head_commit.url }}"
              }' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
