name: Commit Benachrichtigungen

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Sende Commit-Benachrichtigung an Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          include-extras: true
          message: |
            **Repository**: ${{ github.repository }}
            **Branch**: ${{ github.ref }}
            **Committer**: ${{ github.actor }}
            **Commit-Nachricht**: ${{ github.event.head_commit.message }}
            **Änderungen**:
            ${{ github.event.head_commit.added }}
            ${{ github.event.head_commit.modified }}
            ${{ github.event.head_commit.removed }}
          embed: |
            {
              "title": "Commit von {{ commit.author.name }}",
              "description": "{{ commit.description }}",
              "url": "{{ commit.url }}",
              "author": {
                "name": "{{ commit.author.name }}",
                "icon_url": "https://github.com/{{ commit.author.username }}.png"
              },
              "fields": [
                {
                  "name": "Commit Hash",
                  "value": "{{ commit.hash }}",
                  "inline": true
                },
                {
                  "name": "Geänderte Dateien",
                  "value": "{{ commit.modified }}",
                  "inline": true
                }
              ]
            }
          last-commit-only: true
