name: Discord Benachrichtigungen

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Sende Benachrichtigung an Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            **Event**: ${{ github.event_name }}
            **Repository**: ${{ github.repository }}
            **Benutzer**: ${{ github.actor }}
            **URL**: ${{ github.event.head_commit.url }}
