name: Discord Notifications

on:
  pull_request:
    types:
      - opened
      - closed
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Notification to Discord
        uses: Ilshidur/action-discord@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          content: |
            **Event**: ${{ github.event_name }}
            **Repository**: ${{ github.repository }}
            **User**: ${{ github.actor }}
            **URL**: ${{ github.event.pull_request.html_url || github.event.release.html_url || github.event.head_commit.url }}
